#SkyTrade v1.3-SNAPSHOT
#Config version: 2

#If you need any help, feel free to contact us on our Discord server.
#https://discord.gg/AqjjhWjpSk


#General trade settings

trade-usage: "<red>Missing arguments! Usage: /trade <player name>"
trade-offline: "<red>Cannot find player, maybe they've gone offline?"
trade-self-trade: "<red>You can't trade with yourself!"
trade-max-distance: 10
trade-too-far: "<red>You are too far away to trade with that player!"
trade-already-trading: "<red>This player is currently trading!"
trade-request-pending: "<red>You already sent a trade request to this player."
trade-request-sent: "<green>You have sent a trade request to <aqua>%target%<green>."
trade-request-received: "<aqua>%sender% <green>has sent you a trade request. <hover:show_text:'<gold>Click to trade!'><click:run_command:'/trade %sender%'><aqua>Click here</click></hover> <green>to accept!"

trade-successful: "<gold>Trade completed with <aqua>%partner%<gold>!"
#Should the names of traded items be displayed after a trade?
list-traded-item-names: true

#This message is shown even if the player’s balance plus the partner’s offered money would exceed the server’s max money limit, or vice versa.
trade-failed: "<red>The trade failed because one of the players didn’t have enough space in their inventory!"

server-max-money: 9007199254740992

trade-player-cancelled: "<red>You cancelled the trade!"
trade-partner-cancelled: "<gray>%partner% <red>cancelled the trade."


shift-right-click-trade-allowed: true

blacklisted-items:
  - "Server Menu"
  - "Your Profile"
  - "Sheep Pet"

item-blacklisted: "<red>This item cannot be traded!"


#GUI items and their settings

gui-title: "<reset>You                  %partner%"

gui-item-divider:
  name: "<gray>⇦ Your stuff"
  lore:
    - "<gray>Their stuff ⇨"

gui-item-coins-transaction:
  name: "<gold>Coins transaction"
  lore:
    - ""
    - "<yellow>Click to add gold!"

#The texture of the money transaction button changes based on the amount of money offered. You can configure it here
icon-level-1-top: 9999
icon-level-2-top: 999999
icon-level-3-top: 1023999999
icon-level-4-top: 8796093022207

money-transaction-started: "<yellow>Please enter the amount you want!"
money-transaction-invalid-amount: "<red>Invalid amount!"
money-transaction-not-enough-balance: "<red>You don’t have enough balance!"
money-transaction-not-enough-space: "<red>You don’t have enough space for that many coins!"
money-transaction-whole-number-only: "<red>Invalid amount. Please enter a whole number!"

gui-item-pending:
  name: "<yellow>Deal timer! <gray>(<yellow>%pendingleft%<gray>)"
  lore:
    - "<gray>The trade recently changed."
    - "<gray>Please review it before"
    - "<gray>accepting!"

gui-item-new-trade:
  name: "<green>Trading!"
  lore:
    - "<gray>Click an item in your inventory,"
    - "<gray>to offer it for trade."

gui-item-gift:
  name: "<aqua>Gift!"
  lore:
    - "<gray>You are receiving items without"
    - "<gray>offering anything in return."
    - ""
    - "<yellow>Click to accept!"

gui-item-nothing-in-return:
  name: "<yellow>Warning!"
  lore:
    - "<gray>You are offering items without"
    - "<gray>getting anything in return."
    - ""
    - "<yellow>Click to accept anyway!"

gui-item-accept:
  name: "<yellow>Deal!"
  lore:
    - "<gray>All trades are final and cannot"
    - "<gray>be reverted."
    - ""
    - "<green>Make sure to review the trade"
    - "<green>before accepting."
    - ""
    - "<yellow>Click to accept the trade!"

gui-item-accepted:
  name: "<yellow>Deal accepted!"
  lore:
    - "<gray>You accepted the trade. Wait"
    - "<gray>for the other party to accept."
    - ""
    - "<red>Click to cancel!"


gui-item-partner-pending:
  name: "<yellow>Deal timer..."
  lore:
    - "<gray>Trading with <aqua>%partner%<gray>."
    - "<gray>The trade changed recently."

gui-item-partner-new-trade:
  name: "<yellow>New deal."
  lore:
    - "<gray>Trading with <aqua>%partner%<gray>."

gui-item-partner-not-confirmed:
  name: "<yellow>Pending their confirm..."
  lore:
    - "<gray>Trading with <aqua>%partner%<gray>."
    - "<gray>Waiting for them to confirm..."

gui-item-partner-confirmed:
  name: "<green>Other player confirmed."
  lore:
    - "<gray>Trading with <aqua>%partner%<gray>."
    - "<gray>Waiting for you to confirm..."


#Money orb system

moneyorb-def-item:
  name: "<gold>%moneyoffered_formatted% coins"
  lore:
    - "<gray>Lump-sum amount"
    - ""

#How many lines does the previous item's lore have?
moneyorb-def-lore-size: 2

moneyorb-extra-lore:
  - "<gold>Total coins offered:"
  - "<gray>%moneyoffered_formatted%"
  - "<dark_gray>(%moneyoffered_exact%)"

#Advanced settings for the money orb system
#These may be difficult to understand, so if you need any help, feel free to contact us.

small_top: 9999
medium_top: 999999
large_top: 999999999
xlarge_top: 8796093022207

small_size: 10000
medium_size: 10000
large_size: 1000000
xlarge_size: 10000000000
xxlarge_size: 8796093022208
#With the current configuration, up to 9007199254740992 can be transacted.

#Money formatting settings
formatting-language: "en"
formatting-country: "US"
exact-formatting-separator: ","