name: SkyTrade
version: '1.3-SNAPSHOT'
main: me.kart9444.SkyTrade.Main
api-version: '1.21'
authors: [ Kart9444 ]
description: A lightweight and stylish trade plugin for Minecraft servers.
website: https://discord.gg/AqjjhWjpSk
depend: [Vault]
commands:
  trade:
    usage: "/trade <player>"
    permission: skytrade.trade
permissions:
  skytrade.trade:
    default: op